---
title: "Curriculum Vitae"
---

You can download a PDF of my CV here: <a href="CV.pdf#" class="download" title="CV">download</a>. You can also view the most recent version of my CV in Google docs [here](https://docs.google.com/document/d/1n0LoET94ZB4UnBt8x2fbAGGQz_KrbAjMj5boW7jGQYo/edit?usp=sharing).


**My most recent presentations and publications are listed here.**

<br>

# <span style="color:red">Presentations</span>

## 2026 

### Peer-reviewed 

"The semantics of White Hmong (in)definiteness." **[Poster]**. *TripleA*. May 12-15. Vancouver, Canada.

"Anaphora and R-expression interaction." **[Talk]**. *Rules and Exceptions in Anaphoric Processing (RED)*. May 21-22. Brașov, Romania. [Slides]

"Variation of w~v in Cook Islands Māori: A statistical approach." **[Talk]**. *The 33rd Annual Meeting of the Austronesian Formal Linguistics Association,* special Te reo Māori session. Wellington, New Zealand. [Slides]

Sally Akevai Nicholas, Rolando Coto-Solano, <b>Quartz Colvin</b>, Gwendolyn Tait, Violet King. "Using Automatic Speech Recognition for documentation of Cook Island Māori. **[Talk]**. *The 33rd Annual Meeting of the Austronesian Formal Linguistics Association,* special Te reo Māori session. Wellington, New Zealand. [Slides]


### Other Presentations

"Anaphora and R-expression interaction: Insights from Hmong." *RULing 2026*.

"Vowel epenthesis in Cheyenne verb initials." **[Talk]**. *Language at Crossroads*. Rutgers University, New Brunswick, New Jersey, USA.

<br>

## Upcoming...

Ake Nicholas, Rolando Coto Solano, Jean Tekura Mason, Gwendolyn Tait, Violet King, **Quartz Colvin**, Freya Scott, Peter Nicholas. "A dictionary of the function words of Māori ꞌAvaiki Nui and some ongoing orthographic tensions in “paradise”". *Annual Conference of the Linguistic Society of New Zealand 2026 (NZLingSoc2026)*. December 7-8. Wellington, New Zealand.  

<br>


## 2025

### Peer-reviewed 

“The Cheyenne Potential, Irrealis and Conditional Modes.” **[Poster]**. *Mid-Atlantic Colloquium of Studies in Meaning (MACSIM 11)*. John Hopkins University, Baltimore, Maryland, USA.

“A cover analysis of the plural classifier in Hmong.” **[Talk]**. *Sinn und Bedeutung 30*. Goethe University Frankfurt, Frankfurt, Germany. [**[Slides](https://quartz-colvin.github.io/SuB30/)**]

“The semantics of Hmong indefinites.” **[Talk]**. *International Conference on Sino-Tibetan Languages and Linguistics.* Universität Bern, Bern, Switzerland. [**[Slides](https://quartz-colvin.github.io/ICSTLL58/)**]

“The syntax of White Hmong reciprocals and reflexives.” **[Poster]**. *Mismatches in Anaphoric Relations* (RED). Universität Graz, Graz, Austria.


### Other Presentations

"The semantics of Hmong (in)definiteness." *RULing 2025.*

<br>


## 2024

“The Cheyenne Potential, Irrealis and Conditional Modes.” **[Poster]**. *Semantics of Under-represented Languages of the Americas*. Federal University of Santa Catarina, Florianópolis, Brazil.

<br>

# <span style="color:red">Publications</span>

## 2026

Quartz Colvin. "White Hmong Reciprocals and Reflexives." In *RED-2025 Proceedings, Mismatches in Anaphoric Relations*, University Library Graz.
<br>


Quartz Colvin. "A cover analysis of the plural classifier in Hmong." In: Sebastian Walter*, Lennart Fritzsche*, Kurt Erbach, Cécile Meier, and
Manfred Sailer (eds.), *Proceedings of Sinn und Bedeutung 30.* Frankfurt: Goethe University Frankfurt, 221–231.
<br>

<br>



## 2025

Avelino, G., Balihaxi, M., Colvin, Q., Czarnecki, V., Joo, H., Wang, C., Zobarlar, U., Jardine, A. & McCollum, A., (2025) “Editors' Note”, *Proceedings of the Annual Meetings on Phonology 1(1)*. doi: https://doi.org/10.7275/amphonology.3007

<br>

## Upcoming...

***(under review).*** Quartz Colvin. "The Cheyenne Potential, Irrealis and Conditional Modes." To appear in *Proceedings of SULA 13.* 
<br>

***(Under review).*** Quartz Colvin. "Anaphora and R-expression Interaction." To appear in *RED-2026 Proceedings,* University Library Graz. 
<br>

***(Under review).*** Quartz Colvin. "Variation of w-v in Cook Islands Māori: A statistical approach." To appear in *Te Reo.*
<br>

***(Under review).*** Sally Akevai Nicholas, Rolando Coto-Solano, **Quartz Colvin**, Gwendolyn Tait, Violet King. "Using Automatic Speech Recognition for documentation of Cook Islands Māori." To appear in *Te Reo.*

***(Under contract).*** “Phonological domains in Algonquian and other morphologically complex languages.” Includes eight invited chapters on Algonquian languages and five invited chapters on other morphologically complex languages. Oxford University Press.

- Contributor for the following chapters: “Insights from Algonquian”, “Theoretical Insights”, “Cheyenne”

