---
title: "Welcome to my personal website!"
---

I am a linguist from Northwest Arkansas who works on semantics, syntax, morphology and their interfaces, strongly emphasizing language documentation and fieldwork methodologies. Currently I am a third year PhD student at Rutgers University, where most of my recent work has been on nominal structures and semantics in White Hmong (my partner's language).

But, I have worked with a range of languages. The language groups I have experience with are Algonquian (Ojibwe, Cheyenne, Arapaho, Shinnecock), Hmong-Mien (White Hmong), Semitic (Arabic varieties), and Polynesian (Cook Islands Māori).

My language interests during my undergraduate degree at the University of Minnesota were theoretical syntax and Semitic languages (my minor was in Arabic). In a field methods course there, my interest shifted to Algonquian, after working with a Southwest Ojibwe speaker. Since this shift was near the end of my undergraduate program, while I was studying for my masters degree I mainly worked on Plains Algonquian (Cheyenne and Arapaho).

